apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pokeproxy
resources:
  - namespace.yaml
  - pokeproxy.yaml
  - mock.yaml
  - redis.yaml
configMapGenerator:
  - name: pokeproxy-rules
    files: [rules.json]
  - name: pokeproxy-settings
    envs: [pokeproxy.env]
  - name: mock-settings
    envs: [mock.env]
  - name: redis-config
    files: [redis.conf]
