apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - prometheus.yaml
  - grafana.yaml
  - rbac.yaml
configMapGenerator:
  - name: prometheus-config
    namespace: monitoring
    files:
      - prometheus.yml=prometheus/prometheus.yml
      - alerts.yml=prometheus/alerts.yml
  - name: grafana-datasources
    namespace: monitoring
    files:
      - datasource.yaml=grafana/datasource.yaml
  - name: grafana-providers
    namespace: monitoring
    files:
      - dashboards.yaml=grafana/providers.yaml
  - name: grafana-dashboards
    namespace: monitoring
    files:
      - pokeproxy.json=grafana/pokeproxy.json
